title: "gabriel uzquiano"
description: "A simple, static portal outlining my open source offerings."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabriel-uzquiano.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false
highlighter: rouge
