title: ""
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabriel-uzquiano.github.io" # the base hostname & protocol for your site
theme: minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false
highlighter: rouge
