title: "Course Materials and Resources"
description: "Online portal with links to course materials."
url: "https://gabriel-uzquiano.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en-US"
timezone: "America/Los_Angeles"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false

author:
  name: "Gabriel Uzquiano"
    
