title: "gabriel uzquiano"
description: "A simple, static portal outlining my open source offerings."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabriel-uzquiano.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
# Add navigation links to your site using the `nav` key.
# For external links add the `external: true` flag.
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false
highlighter: rouge
